title: Hyungkyu Kim
subtitle: (김형규)
face: /assets/img/hyungkyukim.jpg
description: M.S.student in Image/Video Engineering at Chung-Ang University
location: Seoul, Korea
email: hyung1208 AT cau.ac.kr
homepage: https://github.com/kimhyungkyu-1208/
twitter:
google_scholar:
semantic_scholar:
CV: https://github.com/kimhyungkyu-1208
github: https://github.com/kimhyungkyu-1208
linkedin: https://www.linkedin.com/in/rlagudrb1208/
theme: jekyll-theme-minimal


plugins:
  - jekyll-seo-tag
